# ╭─────────────────────────────────ImplementationGuide-hl7.fhir.uv.RE.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.cl.recetachile
canonical: https://rme.hl7chile.cl
version: 0.9
name: RecetaCL
title: Guía de Implementación Receta-CL
status: draft
date: 2021-07
publisher: Ministerio de Salud, Chile / HL7 Chile
#publisher:
#  name: HL7 Chile
#  url: http://hl7chile.cl
#  email: chair@hl7chile.cl

description: Guía de Implementación para los perfiles de Receta complementarios a los de CORE Nacional, para su uso en Recete Electrónica Nacional. Esta Guía se encuentra aún en proceso de creación por lo que esta versión esta sujeta a observaciones y cambios. Aquellos implementadores que tengan acceso a ella se les sugiere desarrollar comentarios para su mejora)
jurisdiction: urn:iso:std:iso:3166#CL "Chile"
license: CC0-1.0
fhirVersion: 4.0.1

parameters:
  apply-publisher: true
  apply-contact: true
  show-inherited-invariants: false
  usage-stats-opt-out: true
copyrightYear: 2020+
releaseLabel: ci-build

dependencies:
  hl7.fhir.cl.corecl: 1.7.0
#  hl7.fhir.cl.corecl:
#    id: CoreCLDEV
#    uri: https://build.fhir.org/ig/HL7Chile/CL-Core/
#    version: dev

pages:
  index.md:
    title: Inicio
  Alcances-Objetivos.md:
    title: Objetivos
  casos.md:
    title: Casos de uso
  operaciones.md:
    title: Operaciones

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Inicio: index.html
  Objetivos: Alcances-Objetivos.html
  Actores y Casos de Uso: casos.html
  Operaciones y Terminologías: operaciones.html
  Resumen de Artefactos:
    Artefactos: artifacts.html
  Perfiles:
    Prescripción: StructureDefinition-RecetaPrescripcionCl.html
    Dispensación: StructureDefinition-DispensacionMedicamentoCl.html
    Receta: StructureDefinition-RecetaCl.html
#  Ejemplos:
#    Ejemplo Prescripción: StructureDefinition-RecetaPrescripcionCl-examples.html
#    Ejemplo Dispensación: StructureDefinition-DispensacionMedicamentoCl-examples.html
#    Ejemplo de Receta: StructureDefinition-RecetaCl-examples.html
